[package]
name = "config"
version = "0.0.1"
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
toml = "0.7.3"
dirs = "5.0"
colors = { path = "../colors" }
serde = { workspace = true }
log = { workspace = true }